### ISSUE TITLE
pip3 install marklogic_python_api or pip install marklogic_python_api does not work

### ISSUE THREAD

**Issue by ErikHoeven** [marklogic/python_api#89]
Hello i am using Linux Mint and installed pip and pip3 (i don't know what the difference is) when i executing the following command in the terminal "`pip3 install marklogic_python_ap`i"
It returns to the following result:
```
Collecting marklogic_python_api
  Could not find a version that satisfies the requirement marklogic_python_api (from versions: )
No matching distribution found for marklogic_python_api
```
Can you tell me, what can i change to use python for Marlogic

Manny thanks,
Erik

**Comment by ndw** [comment]
I'm still uploading it to the test repository until I think it's really stable. Progress has been delayed by other priorities. Try:

    /usr/bin/pip3 install marklogic_python_api -i https://testpypi.python.org/pypi

**Comment by wblakecannon** [comment]
I'm trying to install this package on a windows machine and I've tried`pip install marklogic_python_api` as well as  `pip install marklogic_python_api -i https://testpypi.python.org/pypi` and either do not work. Is this package still available?
